### ISSUE TITLE
Field help text isn't displayed

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/resource_timeslots#1]
When I add some help text in the configuration form of a *Resource timeslot* field (admin/structure/types/manage/my-content-type/fields/my-field/edit), the text doesn't show up in the content (add or edit) form, no matter if I select a resource (and see the calendar) or not.

**Comment by indigoxela** [comment]
> When I add some help text ... the text doesn't show up

Nice catch, should be fixed in https://github.com/backdrop-contrib/resource_timeslots/commit/c864c391fbf56bb0b59cf88b56698af2e5776aaf

**Comment by olafgrabienski** [comment]
Great, works for me – many thanks!

For the record, the help text shows only up when a resource is selected. Makes sense, in my opinion, because before there is no calendar in the form.

**Comment by olafgrabienski** [comment]
After updating to version [1.x-1.0.0-alpha2](https://github.com/backdrop-contrib/resource_timeslots/releases/tag/1.x-1.0.0-alpha2), the help text doesn't show up anymore.

I hope it's fine to reopen this issue. Let me know if you prefer a new one.

**Comment by indigoxela** [comment]
Sorry, yes, it was gone after the recent rewrite, but should be back now with b241349

**Comment by olafgrabienski** [comment]
Thanks for the quick response! I've applied the commit to my test site, and the help text shows up again.

**Comment by indigoxela** [comment]
Many thanks for testing.
