### ISSUE TITLE
Deleting a slot doesn't work

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/resource_timeslots#13]
I'm not able to delete a timeslot on a touch device. Apparently, it worked a while ago:

> The trick to get the delete button event back, was to tap short outside the selection (dot vanishes). Then the delete button (cross) worked again.

However, for me it's not working, no matter if I select the slot before deleting, or not.

More info: 

- Tested on iPad and iPhone

**Comment by indigoxela** [comment]
FTR: the previous trick was to tap outside the slot to "unblock" the click event (the tiny drag button disappears), but apparently that's not (fully?) working anymore.

![blocked-dot](https://user-images.githubusercontent.com/842066/145982861-5c5c3069-b57d-438c-8adb-176867ba6a7a.png)

It might not be possible to fully fix this, but a workaround could be possible.

> Tested on iPad and iPhone

Great! These are always hard to test for me.

**Comment by indigoxela** [comment]
A PR is available now for testing: #14

I'm curious if this works for iPad and iPhone. Unfortunately I wasn't able to figure out, which change might have broken it. We have to experiment. :wink:

**Comment by olafgrabienski** [comment]
> I'm curious if this works for iPad and iPhone.

Many thanks, it works for both! Interestingly, there's one difference. Using an iPhone, deleting a timeslot works in every situation now, without having to tap 'outside' the slot. On iPad you *have* to tap outside the slot but only if you explicitely tap-selected the slot before, i.e. for changing the time span or moving the slot around.

**Comment by indigoxela** [comment]
> Using an iPhone, deleting a timeslot works in every situation now

Interesting, indeed... I wouldn't have expected that difference between iPhone and iPad.

Does the moving and resizing still work in iPhone? Just to make sure.

**Comment by olafgrabienski** [comment]
> Does the moving and resizing still work in iPhone?

Yes, works as well!
