### ISSUE TITLE
the selected timeslot will dispear after batch update

### ISSUE THREAD

**Issue by websterhung** [backdrop-contrib/resource_timeslots#18]
Hello, thanks for the awesome modudle!

But I found a bug that when a update from admin/content like change node status to promoted, the selected room, selected time will dispear. But when I edited it by single node(/node/15/edit), it works well.

Is anyone have this problem too?

Thanks!

**Comment by indigoxela** [comment]
> when a update from admin/content like change node status to promoted, the selected room, selected time will dispear

Confirmed! Using VBO (like on /admin/content/node) leads to data loss!

Nobody reported that so far, so many thanks that you did @websterhung

**Comment by indigoxela** [comment]
A PR is available for testing: #19

If you're able to apply a patch, [here is it](https://patch-diff.githubusercontent.com/raw/backdrop-contrib/resource_timeslots/pull/19.diff).

Please let me know, if you need any guidance for testing.

**Comment by websterhung** [comment]
@indigoxela  Thanks for your quick reply!
It works!

Thank you so much!!
