### ISSUE TITLE
Re-introduce display of time span(s)

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/resource_timeslots#4]
Before the introduction of [multiple values per field](https://github.com/backdrop-contrib/resource_timeslots/commit/83eaa602c5789bafeb101e29a1a2e566d9110dd3), when I selected a time slot, there was a useful message with the time span displayed below the calendar (`You selected @start to @end`). With the introduction of multi values, the message was replaced with the pattern `@selected slot(s) selected, @avail available`, example: "1 slot(s) selected, 9 available".

I agree that the *number* of selected and available slots is also useful, when choosing multiple values. Paging through the calendar for slots in different weeks, I felt however quite lost not seeing *which* slots I had already selected. So, I'd suggest to introduce the time span display again (and maybe display the number of slots only for multi value fields).

As mentioned in the chat, a list of selected items can get quite exhaustive, so it might be a good idea to put them in a collapsed section. Rough mockup:

**Collapsed:**

```
> 2 slots selected, 4 available
```

**Open:**

```
v 2 slots selected, 4 available

  - Mon 25 Oct 2021, 10 - 12 h
  - Mon 01 Nov 2021, 10 - 12 h
```

**Comment by indigoxela** [comment]
Here's a screenshot of a current dev state (not yet available on Github):

A details element that's per default collapsed - to prevent using too much space. The screenshot shows the expanded state with multiple values.

![screenshot-dates-displayed](https://user-images.githubusercontent.com/842066/138712123-59cf62bb-117f-474c-9711-562d19d91125.png)

Maybe it makes sense to always display it the same way, no matter of field cardinality (also with a single slot) - for visual consistency and (ahem) developer convenience. :wink:

**Comment by olafgrabienski** [comment]
The screenshot looks perfect, thanks a lot!

> Maybe it makes sense to always display it the same way, no matter of field cardinality ...

Sounds reasonable. While on single value fields expanded by default is much more informative and doesn't consume much space, I hear you rightly mentioning developer convenience. Maybe we can revisit this part sometimes as a follow-up.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop-contrib/resource_timeslots/pull/5) is now available, testing is welcome!

**Comment by olafgrabienski** [comment]
Tested, works like a charm, as showed in the screenshot.

Only one strange thing. Not sure if on my test site I'd changed something unconsciously which led to it: After applying the PR, a formerly saved reservation with multiple values behaved somehow strange. I don't remember the details but at a certain point I noticed that the "Number of values" field setting was set to "Limited" (1 value). Is it possible that the setting was reset due to the PR?

**Comment by indigoxela** [comment]
> I don't remember the details but at a certain point I noticed that the "Number of values" field setting was set to "Limited" (1 value). Is it possible that the setting was reset due to the PR?

Unlikely, nothing regarding the field widget settings handling changed in _this_ PR. The value was forced to "1" before the previous PR (Multiple values per field), but is configurable since then. If you find a way to reproduce, please open a new issue for that.

**Comment by indigoxela** [comment]
Thinking the wording over....

> 2 slots selected, 4 available

Isn't "available" a bit misleading? Very likely resource_timeslot is installed to handle availability of something.

Maybe: "2 slots selected, 4 left to choose." @olafgrabienski what do you think?

**Comment by olafgrabienski** [comment]
You're right, "available" is ambiguous in the context of this module.

The phrase "left to choose" sounds a bit awkward to me, but my English isn't the best, so I'm not sure. Possible alternatives: selectable, remaining. Let's see:

> 2 slots selected, 4 selectable

Also ambiguous, as it's not clear if 4 means the maximum or the remaining values. Speaking of "remaining":

> 2 slots selected, 4 remaining

Sounds good to me!

PS: And an alternative with a different approach:

> 2 slots selected (maximum: 6)

**Comment by indigoxela** [comment]
> 2 slots selected, 4 remaining

I love that! :+1:
