### ISSUE TITLE
Allow default value to be resource only without having to set default timeslot

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/resource_timeslots#7]
**Story**
_As a_ resource manager
_I want to_ set a default resource for the most common type of booking without selecting a fixed slot
_So that_ the most common resource can be preselected but the timeslot is not fixed to a time that may be in the past or no where near the current time

**Acceptance criteria**
Given that I am configuring the reservation content type
When I select a resource under Default value
Then I am not prompted to add a timeslot
And the resource appears by default on creation of any new reservation content items

**Comment by indigoxela** [comment]
Yeah, that default value handling was on my todo list.

A default slot will never make sense, but a default resource could. A PR is available, if you want to test. Note that **update.php needs to be run** after applying the patch.

Screenshot:
![default-resource](https://user-images.githubusercontent.com/842066/141441274-39e1f514-7b9f-4127-ba74-462d9a7a7036.png)

(A bit tricky is that the source type is part of the same settings form, but a help text is shown, when that setting is still empty.)

**Comment by yorkshire-pudding** [comment]
I've tested this and it works as per the acceptance criteria.
Thank you.
