### ISSUE TITLE
Allow date format on timeslot calendar to be configured

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/resource_timeslots#8]
*Story*
As a site builder in the UK
I want to set the date format on the booking calendar to UK format (i.e. dd/mm)
So that my users aren't confused

![image](https://user-images.githubusercontent.com/20357797/141332596-3347207f-e203-49f0-ad0a-cbd1e5140691.png)

**Comment by indigoxela** [comment]
Strange... the day headers should get the correct localized format by Fullcalendar. It works for me, but doesn't seem to work for you. Is it the same in different browsers?

There's no setting for it (in FC), so there's probably not much we can do.

![date-formatting](https://user-images.githubusercontent.com/842066/141425355-41ffb358-ef1b-4474-8202-715d59a635b4.png)

**Comment by indigoxela** [comment]
Hm, maybe it's you browser setting. Can you open the dev tools, switch to console and put in `navigator.languages` - what do you get?
![navigator-lang](https://user-images.githubusercontent.com/842066/141426117-85f1e7bd-7779-46d5-91f9-d15823f35be0.png)

**Comment by yorkshire-pudding** [comment]
Get this:
![image](https://user-images.githubusercontent.com/20357797/141436519-6280058b-49cb-404a-8fbb-d1009c8a271e.png)

Quite a puzzle

**Comment by yorkshire-pudding** [comment]
Does the module set [dayHeaderFormat](https://fullcalendar.io/docs/dayHeaderFormat)?
https://stackoverflow.com/questions/61805073/format-column-header-dates-in-fullcalendar

**Comment by indigoxela** [comment]
> Does the module set dayHeaderFormat?

No.

**Comment by indigoxela** [comment]
Oh, and the moment library also isn't part of the module.

**Comment by indigoxela** [comment]
And the setting alone won't change anything, as without additional js libraries, there's no format available.

https://fullcalendar.io/docs/dayHeaderFormat

As I already stated - we probably can't do anything about it. But first I'd like to figure out, why your browser(s) fail to localize the date properly.
Please post your browser name and version. Did you already try different ones? Any errors logged in your browser console. Do you use a custom theme or other contrib modules?

**Comment by yorkshire-pudding** [comment]
Tried Firefox and get the same.  I have Chrome Version 95.0.4638.69 (Official Build) (64-bit) and Firefox 94.0.1 (64-bit)
Same result in both.  Windows setup correctly:
![image](https://user-images.githubusercontent.com/20357797/141443666-4cd036de-4a59-4969-8eed-88c2b020cc18.png)
![image](https://user-images.githubusercontent.com/20357797/141443854-7e8430fa-63df-47cb-8cb7-24e2b5be2488.png)

And site settings
![image](https://user-images.githubusercontent.com/20357797/141443915-93ce12ac-a32b-4657-8d9b-3926b1b6c194.png)
![image](https://user-images.githubusercontent.com/20357797/141444022-7a06322d-4f92-4f50-a5e3-9fa2ba5b4d94.png)

**Comment by yorkshire-pudding** [comment]
No errors in console except "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'." which seems to be site wide

**Comment by yorkshire-pudding** [comment]
I'm using Seven in Admin pages.  Got quite a few contrib themes but not sure of any that might clash with this

**Comment by indigoxela** [comment]
Hm, if both, Firefox and Chrome do the same, it's rather a system thing.

The site's date formats don't have any influence here, as the rendering happens completely in the browser. Didn't find any related issue in the Fullcalendar queue. (The interest-cohort thing is harmless and unrelated.)

So we probably have to wait until someone figures out what's happening.
Crazy idea, can you try it on a different device, like a smartphone or tablet?

And yet another little console task: `var foo = new Intl.DateTimeFormat(); foo.format();` What does this output for you?

**Comment by yorkshire-pudding** [comment]
![image](https://user-images.githubusercontent.com/20357797/141448135-408483ea-6b79-4246-bc8c-d83b294d6c3b.png)

**Comment by yorkshire-pudding** [comment]
Phone and tablet the same

**Comment by yorkshire-pudding** [comment]
Have tried disabling all extensions in browser also.

**Comment by indigoxela** [comment]
OK, I think I got it - it's about Fullcalendar **locale** setting.

That's a bit tricky. English as installed in Backdrop has the language code "en", which also provides the language prefix in urls.
What you need would be "en-gb". The language "English, British" (en-gb) is also available for language selection, but I don't think it's acceptable to force all people in UK to switch the language, just to get proper date formats in a js calendar.

There is an api hook to extend the js settings in resource-ts.js, but I also don't think it's acceptable to implement that just for the proper date/month order.

My conclusion: the module has to fix it. Not sure yet, how.

**Comment by yorkshire-pudding** [comment]
Note - as I only use English, I don't have language module enabled so had to change in config

I can confirm that:

1. going to `admin/config/development/configuration/single/export` 
2. select Configuration for Configuration group
3. select System core settings
4. Copy all to clipboard
5. switch to import
6. paste
7. find language_default
8. Add -gb to en
9. Click import

then the date format in resource timeslot is correct.  As you say, not acceptable that users have to do that.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop-contrib/resource_timeslots/pull/11) is available for testing. (It's a workaround.)

**Comment by yorkshire-pudding** [comment]
Works great.  Thank you.
