### ISSUE TITLE
Guidance on format of JSON feed for additional reserved slots

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/resource_timeslots#9]
The URL for additional reserved slots looks interesting, but it could do with more guidance somewhere as to what that JSON feed would look like, perhaps with examples.

![image](https://user-images.githubusercontent.com/20357797/141333284-912b63a9-ff11-4d37-a157-38d688bd2310.png)

**Comment by indigoxela** [comment]
That's true, this really needs some documentation.

Probably the easiest way is with [views_json](https://github.com/backdrop-contrib/views_json) (that module has no stable release yet), but you can also code it.

The [FullCalendar docs regarding event feed](https://fullcalendar.io/docs/events-json-feed)

**Comment by indigoxela** [comment]
Update: views_json does have a stable release for some weeks now.

Maybe interesting: why an additional feed, anyway?

That feed can be helpful to also show slots from other sources as blocked in the widget. That could be something from regular date fields, or could also be another resource_timeslot field with different settings (different max values, different business hours...

The only important thing to know is how FullCalendar (which queries that feed via GET) needs the data, but the format isn't complicated:

- start: a date in a js-parsable format
- end: a date in a js-parsable format
- display: background

The latter (display: background) can be accomplished with a "Global: custom text" views field. The rest is trial and error.

And now it should be clear, why developers should *never* write documentation for their own stuff. :laughing:

**Comment by yorkshire-pudding** [comment]
I'm happy to write something up on the basis of what you've provided.  Should this be in the Readme or should it go in a wiki?  I think there are loads of possible use cases, so happy to pick this up.

**Comment by indigoxela** [comment]
> I'm happy to write something up

Cool! Many thanks.

> Should this be in the Readme or should it go in a wiki?

Good question, probably the wiki. It's way easier to handle things like screenshots in the wiki. I just enabled it for this repo. Do you have permission to edit? Are you member of backdrop-contrib/authors?

**Comment by yorkshire-pudding** [comment]
Yes, got permission.  I'll get something up later this week.

**Comment by indigoxela** [comment]
> I'll get something up later this week.

No need to hurry, I'm just happy that I don't have to do it. And - belief me - the users will be happy, too. :smirk:

**Comment by yorkshire-pudding** [comment]
Wiki page here - https://github.com/backdrop-contrib/resource_timeslots/wiki/Reserve-slots-with-a-JSON-feed
